# load balancing for multiple bookmark_service, with port open
upstream bookmark_service {
    server bookmark_service:8080;
}

upstream portal {
    server portal:3000;
}
server {
    listen 80;
    server_name bookmark_service;
    # provide portal upstream call
    location / {
        proxy_pass http://portal/;
    }
    # provide bookmark_service upstream call
    location /api/bookmark_service {
        proxy_pass http://bookmark_service/;
    }
}