name: cd-pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  cd_pipeline_bookmark_service:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          # Không dùng "<<", truyền chuỗi lệnh trực tiếp sau thông tin user@host
          # Bỏ tham số "-tt" để SSH chạy ở chế độ phi tương tác (Non-interactive), tự động CLOSE khi hết lệnh
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=15 \
            -o ServerAliveCountMax=3 \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
              echo 'Connected via sshpass'
              cd /app/golang-deployment || exit 1
              git fetch
              git checkout main
              git pull origin main
              cd deployment || exit 1
              docker compose pull bookmark_service
              docker compose up -d --remove-orphans bookmark_service
              docker system prune -f
              exit 0
            "
