name: cd-pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  cd_pipeline_bookmark_service:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -tt \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=15 \
            -o ServerAliveCountMax=120 \
            -o TCPKeepAlive=yes \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
              echo 'Connected via sshpass'
              cd /app/golang-deployment
              git fetch
              git checkout main
              git pull origin main
              cd deployment
              docker ps -f "name=bookmark_service" --format '{{.Names}}' | grep -q bookmark_service && docker rm -f bookmark_service
              docker compose pull bookmark_service
              docker compose up -d --remove-orphans bookmark_service
              docker system prune -f
              # Ép đóng phiên SSH trên server để trả quyền điều khiển về cho GitHub Runner
              exit 0
          EOF
